// <auto-generated />
using System;
using ChronoLog.SqlDatabase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoLog.SqlDatabase.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.EmployeeEntity", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("DailyWorkingTimeInHours")
                        .HasColumnType("double");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsProjectManager")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<double>("OvertimeCorrectionInHours")
                        .HasColumnType("double");

                    b.Property<int>("Province")
                        .HasColumnType("int");

                    b.Property<int>("VacationDaysPerYear")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultResponseText")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("ResponseObject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjecttimeEntity", b =>
                {
                    b.Property<Guid>("ProjecttimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseText")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjecttimeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("Projecttimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorkdayEntity", b =>
                {
                    b.Property<Guid>("WorkdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("WorkdayId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorktimeEntity", b =>
                {
                    b.Property<Guid>("WorktimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan?>("BreakTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("char(36)");

                    b.HasKey("WorktimeId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("Worktimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjecttimeEntity", b =>
                {
                    b.HasOne("ChronoLog.SqlDatabase.Models.ProjectEntity", "Project")
                        .WithMany("Projecttimes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChronoLog.SqlDatabase.Models.WorkdayEntity", "Workday")
                        .WithMany("Projecttimes")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Project");

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorkdayEntity", b =>
                {
                    b.HasOne("ChronoLog.SqlDatabase.Models.EmployeeEntity", "Employee")
                        .WithMany("Workdays")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorktimeEntity", b =>
                {
                    b.HasOne("ChronoLog.SqlDatabase.Models.WorkdayEntity", "Workday")
                        .WithMany("Worktimes")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.EmployeeEntity", b =>
                {
                    b.Navigation("Workdays");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjectEntity", b =>
                {
                    b.Navigation("Projecttimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorkdayEntity", b =>
                {
                    b.Navigation("Projecttimes");

                    b.Navigation("Worktimes");
                });
#pragma warning restore 612, 618
        }
    }
}
