// <auto-generated />
using System;
using ChronoLog.SqlDatabase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoLog.SqlDatabase.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    partial class SqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("DefaultResponseText")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseObject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProjectId");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjecttimeEntity", b =>
                {
                    b.Property<Guid>("ProjecttimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResponseText")
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("TimeSpent")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("char(36)");

                    b.HasKey("ProjecttimeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("Projecttimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorkdayEntity", b =>
                {
                    b.Property<Guid>("WorkdayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("WorkdayId");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorktimeEntity", b =>
                {
                    b.Property<Guid>("WorktimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("BreakTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("char(36)");

                    b.HasKey("WorktimeId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("Worktimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjecttimeEntity", b =>
                {
                    b.HasOne("ChronoLog.SqlDatabase.Models.ProjectEntity", "Project")
                        .WithMany("Projecttimes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ChronoLog.SqlDatabase.Models.WorkdayEntity", "Workday")
                        .WithMany("Projecttimes")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorktimeEntity", b =>
                {
                    b.HasOne("ChronoLog.SqlDatabase.Models.WorkdayEntity", "Workday")
                        .WithMany("Worktimes")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.ProjectEntity", b =>
                {
                    b.Navigation("Projecttimes");
                });

            modelBuilder.Entity("ChronoLog.SqlDatabase.Models.WorkdayEntity", b =>
                {
                    b.Navigation("Projecttimes");

                    b.Navigation("Worktimes");
                });
#pragma warning restore 612, 618
        }
    }
}
